📄TEMPLATE | ⏰¹ | 👩‍💻 Fixed `src/main.ts:260:3 - error TS2353: Object literal may only specify known properties, and 'version' does not exist in type '{ type: string; name: string; description: string; preview?: boolean | undefined; }'.`, which failed the pipeline.
¹) taken from https://github.com/luckydonald/hoass_calendar-alarm-clock/commit/85753ef54a697972737f46cfecd7acefda391ed7)